package com.gososmed.agent

import org.junit.Assert.*
import org.junit.Test
import java.io.File

class DebugFrameEncoderTest {

    @Test
    fun testMetadataSerialization() {
        val metadata = DebugFrameEncoder.FrameMetadata(
            binaryMessageId = "bin-1234",
            frameSeq = 100L,
            timestampMs = 1718000000000L,
            format = "jpeg",
            width = 1080,
            height = 2400,
            quality = 70,
            byteLength = 45000
        )

        val json = metadata.toJson()
        assertEquals("bin-1234", json.getString("binary_message_id"))
        assertEquals(100L, json.getLong("frame_seq"))
        assertEquals(45000, json.getInt("byte_length"))

        val parsed = DebugFrameEncoder.FrameMetadata.fromJson(json)
        assertEquals(metadata, parsed)
    }

    @Test
    fun testBoundedQueueEnqueueAndPoll() {
        val queue = DebugFrameEncoder.BoundedFrameQueue(maxCapacity = 3)
        val data1 = byteArrayOf(1, 2, 3)
        val meta1 = DebugFrameEncoder.FrameMetadata("f1", 1L, 1000L, "jpeg", 100, 100, 50, 3)

        queue.enqueue(data1, meta1)
        val stats1 = queue.stats()
        assertEquals(1L, stats1.enqueuedCount)
        assertEquals(1, stats1.currentQueueSize)

        val polled = queue.poll()
        assertNotNull(polled)
        assertEquals("f1", polled?.metadata?.binaryMessageId)
        assertArrayEquals(data1, polled?.data)

        val stats2 = queue.stats()
        assertEquals(1L, stats2.sentCount)
        assertEquals(0, stats2.currentQueueSize)
    }

    @Test
    fun testDropOldestOnCapacityOverflow() {
        val capacity = 3
        val queue = DebugFrameEncoder.BoundedFrameQueue(maxCapacity = capacity)

        // Enqueue 5 frames into capacity 3
        for (i in 1..5) {
            val data = byteArrayOf(i.toByte())
            val meta = DebugFrameEncoder.FrameMetadata("f$i", i.toLong(), 1000L + i, "jpeg", 100, 100, 50, 1)
            queue.enqueue(data, meta)
        }

        val stats = queue.stats()
        assertEquals(5L, stats.enqueuedCount)
        assertEquals(2L, stats.droppedCount) // 5 - 3 = 2 dropped
        assertEquals(3, stats.currentQueueSize)

        // Oldest frames f1 and f2 must have been dropped; f3, f4, f5 remain
        val polled1 = queue.poll()
        assertEquals("f3", polled1?.metadata?.binaryMessageId)
        val polled2 = queue.poll()
        assertEquals("f4", polled2?.metadata?.binaryMessageId)
        val polled3 = queue.poll()
        assertEquals("f5", polled3?.metadata?.binaryMessageId)
        assertNull(queue.poll())
    }

    @Test
    fun testAcknowledgeTracking() {
        val queue = DebugFrameEncoder.BoundedFrameQueue(maxCapacity = 3)
        val meta = DebugFrameEncoder.FrameMetadata("f-ack", 1L, 1000L, "jpeg", 100, 100, 50, 1)
        queue.enqueue(byteArrayOf(10), meta)

        assertFalse(queue.acknowledge("f-ack")) // not yet polled/sent

        val polled = queue.poll()
        assertNotNull(polled)

        assertTrue(queue.acknowledge("f-ack")) // successfully acknowledged
        assertFalse(queue.acknowledge("f-ack")) // cannot double-ack

        val stats = queue.stats()
        assertEquals(1L, stats.ackedCount)
        assertEquals(1L, stats.sentCount)
    }

    @Test
    fun testZeroDiskWritesDuringEncodeAndQueue() {
        val tempDir = File(System.getProperty("java.io.tmpdir") ?: ".")
        val initialFiles = tempDir.list()?.toSet() ?: emptySet()

        val compressor = DebugFrameEncoder.SimulatedFrameCompressor()
        val rawPixels = ByteArray(1024) { (it % 128).toByte() }
        val compressed = compressor.compress(rawPixels, 64, 16, "webp", 80)

        val meta = DebugFrameEncoder.FrameMetadata(
            binaryMessageId = "bin-memory-only",
            frameSeq = 42L,
            timestampMs = System.currentTimeMillis(),
            format = "webp",
            width = 64,
            height = 16,
            quality = 80,
            byteLength = compressed.size
        )

        val queue = DebugFrameEncoder.BoundedFrameQueue(maxCapacity = 2)
        queue.enqueue(compressed, meta)
        val polled = queue.poll()
        assertNotNull(polled)
        queue.acknowledge("bin-memory-only")

        val currentFiles = tempDir.list()?.toSet() ?: emptySet()
        // No new temporary files should be created by our frame encoder / queue
        val createdTempFiles = currentFiles - initialFiles
        assertTrue("No disk files should be generated by frame pipeline", createdTempFiles.isEmpty())
    }

    @Test
    fun testCapacityZeroOrNegativeHandledSafely() {
        val queueZero = DebugFrameEncoder.BoundedFrameQueue(maxCapacity = 0)
        assertEquals(1, queueZero.maxCapacity)

        val queueNeg = DebugFrameEncoder.BoundedFrameQueue(maxCapacity = -10)
        assertEquals(1, queueNeg.maxCapacity)

        val data = byteArrayOf(1, 2, 3)
        val meta = DebugFrameEncoder.FrameMetadata("f0", 1L, 1000L, "jpeg", 100, 100, 50, 3)
        assertTrue(queueZero.enqueue(data, meta))
        assertEquals(1, queueZero.stats().currentQueueSize)
        val polled = queueZero.poll()
        assertNotNull(polled)
        assertEquals(0, queueZero.stats().currentQueueSize)
    }

    @Test
    fun testFrameEnqueuedProducesValidByteSize() {
        val queue = DebugFrameEncoder.BoundedFrameQueue(maxCapacity = 5)
        val bytes = byteArrayOf(10, 20, 30, 40, 50, 60, 70, 80)
        val meta = DebugFrameEncoder.FrameMetadata("f-size", 1L, 1000L, "webp", 320, 240, 80, bytes.size)

        queue.enqueue(bytes, meta)
        val polled = queue.poll()
        assertNotNull(polled)
        assertEquals(bytes.size, polled?.data?.size)
        assertEquals(bytes.size, polled?.metadata?.byteLength)
    }

    @Test
    fun testInFlightAckTimeoutCleanup() {
        val queue = DebugFrameEncoder.BoundedFrameQueue(maxCapacity = 5)
        val bytes = byteArrayOf(1, 2)
        val meta = DebugFrameEncoder.FrameMetadata("f-leak", 1L, 1000L, "jpeg", 100, 100, 50, 2)

        queue.enqueue(bytes, meta)
        val polled = queue.poll()
        assertNotNull(polled)
        assertEquals(1, queue.inFlightAckCount())

        // Within timeout (5s < 10s timeout) -> should not evict
        val now = System.currentTimeMillis()
        val evictedBefore = queue.evictExpiredAcks(timeoutMs = 10_000L, currentTimeMs = now + 5_000L)
        assertEquals(0, evictedBefore)
        assertEquals(1, queue.inFlightAckCount())

        // After timeout (11s > 10s timeout) -> should evict
        val evictedAfter = queue.evictExpiredAcks(timeoutMs = 10_000L, currentTimeMs = now + 11_000L)
        assertEquals(1, evictedAfter)
        assertEquals(0, queue.inFlightAckCount())

        // Subsequent acknowledge must fail because it was evicted
        assertFalse(queue.acknowledge("f-leak"))
    }
}
